---
- name: Create API network port
  os_port:
    name: "{{ os_port_api }}"
    network: "{{ os_network }}"
    security_groups:
      - "{{ os_master_secgrp }}"
    fixed_ips:
      - subnet: "{{ os_subnet }}"
        ip_address: "{{ subnet_range | next_nth_usable(5) }}"

- name: Create Ingress network port
  os_port:
    name: "{{ os_port_ingress }}"
    network: "{{ os_network }}"
    security_groups:
      - "{{ os_worker_secgrp }}"
    fixed_ips:
      - subnet: "{{ os_subnet }}"
        ip_address: "{{ subnet_range | next_nth_usable(7) }}"
