---
- name: Set os_network variable
  set_fact:
    os_network: "{{ openshift_cluster_id }}-ocp4-network"

- name: Set os_subnet variable
  set_fact:
    os_subnet: "{{ openshift_cluster_id }}-ocp4-nodes"

- name: Set os_external_router variable
  set_fact:
    os_external_router: "{{ openshift_cluster_id }}-ocp4-router"

- name: Set os_master_secgrp variable
  set_fact:
    os_master_secgrp: "{{ openshift_cluster_id }}-ocp4-master"

- name: Set os_worker_secgrp variable
  set_fact:
    os_worker_secgrp: "{{ openshift_cluster_id }}-ocp4-worker"

- name: Set os_port_api variable
  set_fact:
    os_port_api: "{{ openshift_cluster_id }}-ocp4-api-port"

- name: Set os_port_ingress variable
  set_fact:
    os_port_ingress: "{{ openshift_cluster_id }}-ocp4-ingress-port"
