---
- name: Create openstack-upi directory locally
  local_action: file path="{{ openshift_upi_directory }}" state=directory mode="0755"

- name: Verify if .openshift_install_state.json exists
  local_action: stat path="{{ openshift_upi_directory }}/.openshift_install_state.json"
  register: openshift_install_stat

- name: Create install-config.yaml locally
  local_action: template src=install-config.yaml.j2 dest="{{ openshift_upi_directory }}/install-config.yaml" mode='0644'
  when: openshift_install_stat.stat.isreg is not defined

- name: Verify if manifests directory exists
  local_action: stat path="{{ openshift_upi_directory }}/manifests"
  register: upi_manifests_directory_stat

- name: Create openshift-installer manifests
  local_action: shell cd {{ openshift_upi_directory }} && openshift-install create manifests
  when: (upi_manifests_directory_stat.stat.isdir is not defined) and (openshift_install_stat.stat.isreg is not defined)

- name: Verify if is necessary to remove master Machines configs
  local_action: stat path="{{ openshift_upi_directory }}/openshift/99_openshift-cluster-api_master-machines-0.yaml"
  register: machines_stat

- name: Verify if is necessary to remove master MachineSets configs
  local_action: stat path="{{ openshift_upi_directory }}/openshift/99_openshift-cluster-api_worker-machineset-0.yaml"
  register: machinesets_stat

- name: Remove Machines
  local_action: shell rm -f "{{ openshift_upi_directory }}"/openshift/99_openshift-cluster-api_master-machines-*.yaml
  when: machines_stat.stat.isreg is defined

- name: Remove MachineSets
  local_action: shell rm -f "{{ openshift_upi_directory }}"/openshift/99_openshift-cluster-api_worker-machineset-*.yaml
  when: machinesets_stat.stat.isreg is defined

- name: Make control-plane nodes unschedulable
  local_action: template src=cluster-scheduler-02-config.yml.j2 dest="{{ openshift_upi_directory }}/manifests/cluster-scheduler-02-config.yml" mode='0644'
  when: openshift_install_stat.stat.isreg is not defined


# Include custom MachineConfig Operator files, that allows necessary modifications of the RHCOS
- name: Include Custom MCO files
  include_tasks: machineconfiguration_files.yml
  when: openshift_install_stat.stat.isreg is not defined


- name: Remove install-config file
  local_action: file path="{{ openshift_upi_directory }}/install-config.yaml state=absent"
  ignore_errors: true

- name: Verify if manifests directory exists
  local_action: stat path="{{ openshift_upi_directory }}/bootstrap.ign"
  register: upi_ignition_file_stat

- name: Create ignition configs
  local_action: shell cd {{ openshift_upi_directory }} && openshift-install create ignition-configs
  when: openshift_install_stat.stat.isreg is not defined

- name: Register clusterID from metadata.json
  local_action: shell cat {{ openshift_upi_directory }}/metadata.json | awk -F , '{print $3}' | cut -d ":" -f 2 | cut -d \" -f 2
  register: clusterID_reg

- name: Set openshift_cluster_id variable
  set_fact:
    openshift_cluster_id: "{{ clusterID_reg.stdout }}"
